# .travis.yml
#
# Copyright (C) 2020 Stephen G. Tuggy and other vsUTCS contributors
#
# This file is part of Vega Strike: Upon the Coldest Sea ("vsUTCS").
#
# vsUTCS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# vsUTCS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsUTCS.  If not, see <https://www.gnu.org/licenses/>.


language: cpp
os: linux

services:
  - docker

git:
  submodules: false

dist: focal

# When updating be sure to add a section
# to the matrix to cover the distro
jobs:
    include:
        - os: linux
          name: "Ubuntu 20.04 focal"
          env:
            - FROM='ubuntu:focal'
        - os: linux
          name: "Ubuntu 18.04 bionic"
          env:
            - FROM='ubuntu:bionic'
        - os: linux
          name: "Ubuntu 16.04 xenial"
          env:
            - FROM='ubuntu:xenial'
        - os: linux
          name: "Debian 10 buster"
          env:
            - FROM='debian:buster'
        - os: linux
          name: "Debian 9 stretch"
          env:
            - FROM='debian:stretch'
        - os: linux
          name: "openSUSE Leap 15.2"
          env:
            - FROM='opensuse/leap'
        - os: linux
          name: "Fedora 32"
          env:
            - FROM='fedora:32'
        - os: linux
          name: "Fedora 31"
          env:
            - FROM='fedora:31'
        - os: linux
          name: "Fedora 30"
          env:
            - FROM='fedora:30'
        - os: linux
          name: "CentOS 8"
          env:
            - FROM='centos:8'
        # - os: osx
        #   osx_image: xcode11.3
        #   env:
        #     - FLAGS='-DUSE_PYTHON_3=OFF -DBoost_NO_BOOST_CMAKE=ON'
        # - os: osx
        #   osx_image: xcode11.3
        #   env:
        #     - FLAGS='-DUSE_PYTHON_3=ON'
    fast_finish: true

script:
  - script/cibuild

deploy:
    # Use DPL V2
    edge: true
    # GitHub Releases
    provider: releases
    token: $GITHUB_TOKEN
    file_glob: true
    file:
       # Upload files in the `packages` directory
       - ./packages/*
#    # release is a draft so it can be edited, updated, etc.
#    # Not needed as we'll do that manually when we'll begin the release.
#    draft: true
#    prerelease: true
#    # GitHub Releases requires a tag; this guarantees a tag is set
    on:
        tags: true
        repo: vegastrike/Assets-Production
